src/Entity/Traits/CreatedTrait.php
<?php


namespace App\Entity\Traits;


use App\Utils\Config;

Trait CreatedTrait
{
	/**
	 * @var int
	 * @ORM\Column(name="created_at", type="integer", nullable=false)
	 */
	private $createdAt;

	/**
	 * Get createdAt
	 *
	 * @param bool $formatted
	 * @return int
	 */
	public function getCreatedAt($formatted = true)
	{
		if ($formatted) {
			return $this->createdAt ? date(Config::DATETIME_FORMAT, $this->createdAt) : null;
		}
		return $this->createdAt;
	}

	/**
	 * @return string
	 */
	public function getCreatedAtFormatted() {
		return $this->getCreatedAt(true);
	}

	/**
	 * @return string
	 */
	public function getCreatedAtDateFormatted() {
		return date(Config::DATE_FORMAT, $this->createdAt);
	}

	/**
	 * Set createdAt
	 *
	 * @param int $createdAt | null
	 *
	 * @return $this
	 */
	public function setCreatedAt($createdAt = null)
	{
		if ($createdAt == null) {
			$this->createdAt = time();
		} else {
			$this->createdAt = $createdAt;
		}

		return $this;
	}


}

src/Entity/Traits/UpdatedAtTrait.php
<?php


namespace App\Entity\Traits;


use App\Utils\Config;

trait UpdatedAtTrait
{
	/**
	 * @var int
	 * @ORM\Column(name="updated_at", type="integer", nullable=true)
	 */
	private $updatedAt;

	/**
	 * Get updatedAt
	 *
	 * @param bool $formatted
	 * @return int
	 */
	public function getUpdatedAt($formatted = true)
	{
		if ($formatted) {
			return $this->updatedAt ? date(Config::DATETIME_FORMAT, $this->updatedAt) : null;
		}
		return $this->updatedAt;
	}

	/**
	 * @return string
	 */
	public function getUpdatedAtFormatted() {
		return $this->getUpdatedAt(true);
	}

	/**
	 * Set updatedAt
	 *
	 * @param int $updatedAt|null
	 *
	 * @return $this
	 */
	public function setUpdatedAt($updatedAt = null) : self
	{
		if ($updatedAt == null) {
			$this->updatedAt = time();
		} else {
			$this->updatedAt = $updatedAt;
		}
		return $this;
	}
}

src/Controller/OfferController.php
<?php


namespace App\Controller;

use App\Repository\FeedRepository;
use App\Repository\OfferRepository;
use App\Service\OfferService;
use App\Utils\Config;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/offer")
 */
class OfferController extends BaseController
{
	/**
	 * @var OfferService
	 */
	private $offerService;

	/**
	 * @var PaginatorInterface
	 */
	private $paginator;

	/**
	 * @var ParameterBagInterface
	 */
	private $parameterBag;

	/**
	 * OfferController constructor.
	 * @param PaginatorInterface $paginator
	 * @param ParameterBagInterface $parameterBag
	 * @param OfferService $offerService
	 */
	public function __construct(PaginatorInterface $paginator, ParameterBagInterface $parameterBag, OfferService $offerService) {
		$this->paginator = $paginator;
		$this->offerService = $offerService;
		$this->parameterBag = $parameterBag;
	}

	/**
	 * @Route("/", name="offer_index", methods="GET")
	 * @param Request $request
	 * @param OfferRepository $offerRepository
	 * @return Response
	 */
	public function indexAction(Request $request, OfferRepository $offerRepository) {
		$data = [
			'title' => 'Offers',
			'wsHost' => $this->parameterBag->get('ws_host'),
			'wsPort' => $this->parameterBag->get('ws_port'),
			'form' => [
				'search' => [
					'sourceUrl' => $request->query->get('sourceUrl', ''),
					'name' => $request->query->get('offerName', ''),
					'feedId' => $request->query->get('feedId', ''),
				],
				'orderBy' => [
					'field' => $request->get('orderByField', 'id'),
					'order' => $request->get('orderByOrder', 'desc'),
				],
				'page' => $request->query->getInt('page', 1),
			]
		];

		$feedQuery = $offerRepository->findOfferQuery($data['form']['search'], $data['form']['orderBy']);
		$data['pagination'] = $this->paginator->paginate($feedQuery, $data['form']['page'], Config::PAGE_LIMIT);
		return $this->render('offer/index.html.twig', $data);
	}
}

templates/offer/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Search Offer</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" id="searchForm">
                    <input type="hidden" name="orderByField" value="{{form.orderBy.field}}" />
                    <input type="hidden" name="orderByOrder" value="{{form.orderBy.order}}" />
                    <div class="box-body">
                        <div class="form-group col-md-3">
                            <label class="col-sm-4 control-label">Feed Id</label>
                            <div class="col-sm-8">
                                <input type="text" name="feedId" class="form-control" value="{{ form.search.feedId }}"
                                       placeholder="Search by feed id">
                            </div>
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-sm-4 control-label">Name</label>
                            <div class="col-sm-8">
                                <input type="text" name="offerName" class="form-control" value="{{ form.search.name }}"
                                       placeholder="Search by offer name">
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-2">
                                <input class="form-control btn btn-primary" type="submit" value="Search"/>
                            </div>
                            <div class="col-md-2">
                                <a class="form-control btn btn-danger" href="{{ path('offer_index') }}" type="button">Reset</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.box -->
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    {% include "app.session.flashbag.html.twig" %}
                    <h3 class="box-title">Total: ({{ pagination.getTotalItemCount }})</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table id="offer-table" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th class="col-md-2">Image</th>
                                <th class="col-md-1">
                                    <a id="sortId" href="javascript:void(0)">ID</a>
                                    {% if form.orderBy.field == 'id' %}
                                        {% if form.orderBy.order == 'asc' %}
                                            <span class="fa fa-sort-asc text-red"></span>
                                        {% elseif form.orderBy.order == 'desc' %}
                                            <span class="fa fa-sort-desc text-red"></span>
                                        {% endif %}
                                    {% endif %}
                                </th>
                                <th class="col-md-1">Offer ID</th>
                                <th class="col-md-2">
                                    <a id="sortName" href="javascript:void(0)">Name</a>
                                    {% if form.orderBy.field == 'name' %}
                                        {% if form.orderBy.order == 'asc' %}
                                            <span class="fa fa-sort-asc text-red"></span>
                                        {% elseif form.orderBy.order == 'desc' %}
                                            <span class="fa fa-sort-desc text-red"></span>
                                        {% endif %}
                                    {% endif %}
                                </th>
                                <th class="col-md-1">
                                    <a id="sortCashBack" href="javascript:void(0)">Cash Back</a>
                                    {% if form.orderBy.field == 'cashBack'  %}
                                        {% if form.orderBy.order == 'asc' %}
                                            <span class="fa fa-sort-asc text-red"></span>
                                        {% elseif form.orderBy.order == 'desc' %}
                                            <span class="fa fa-sort-desc text-red"></span>
                                        {% endif %}
                                    {% endif %}
                                </th>
                                <th class="col-md-2">Updated</th>
                                <th class="col-md-2">Created</th>
                                <th class="col-md-1">Update Feed</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% if pagination.getTotalItemCount %}
                                {% for item in pagination %}
                                    <tr>
                                        <td>
                                            {% if (item.imageUrl) %}
                                                <img class="img img-responsive" width="50px" height="50px"
                                                     src="{{ item.imageUrl }}">
                                            {% endif %}
                                        </td>
                                        <td>{{ item.id }}</td>
                                        <td>{{ item.offerId }}</td>
                                        <td>{{ item.name }}</td>
                                        <td>{{ item.cashBack }}</td>
                                        <td>{{ item.updatedAtFormatted }}</td>
                                        <td>{{ item.createdAtFormatted }}</td>
                                        <td>{{ item.updateFeed.id }}</td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="12" class="alert">No records found</td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix">
                    <div class="no-margin pull-right">
                        {{ knp_pagination_render(pagination) }}
                    </div>
                </div>
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

    {% if form.search.feedId is defined and form.search.feedId > 0 %}
    {% include "popup.modal.html.twig" with {feedId: form.search.feedId, wsHost: wsHost, wsPort: wsPort} %}
    {% endif %}

    <script>
        function toggleSort(sortInput) {
            let order = sortInput.val();
            if (order === 'asc') {
                sortInput.val('desc');
            } else if (order === 'desc') {
                sortInput.val('asc');
            }
            $('#searchForm').submit();
        }

        $(document).ready(function() {
            $('#sortCashBack').on('click', function() {
                $('input[name=orderByField]').val('cashBack');
                toggleSort($('input[name=orderByOrder]'));
            })
            $('#sortName').on('click', function() {
                $('input[name=orderByField]').val('name');
                toggleSort($('input[name=orderByOrder]'));
            })
            $('#sortId').on('click', function() {
                $('input[name=orderByField]').val('id');
                toggleSort($('input[name=orderByOrder]'));
            })
        });

    </script>
{% endblock %}