src/Entity/FeedEntity.php
<?php


namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\CreatedTrait;
use App\Entity\Traits\IdTrait;


/**
 * @ORM\Entity(repositoryClass="App\Repository\FeedRepository")
 * @ORM\Table(name="feed")
 */
class FeedEntity
{
	use IdTrait;
	use CreatedTrait;

	/**
	 * @var string
	 * @ORM\Column(type="string", nullable=false)
	 */
	private $sourceUrl;

	/**
	 * @var string
	 * @ORM\Column(type="string", nullable=false)
	 */
	private $status;


	/**
	 * @var string|null
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $url;

	/**
	 * @var bool
	 * @ORM\Column(name="skip_error", type="boolean", nullable=false)
	 */
	private $skipError;

	/**
	 * @var bool
	 * @ORM\Column(name="force_update", type="boolean", nullable=false)
	 */
	private $forceUpdate;

	/**
	 * @var bool|null
	 * @ORM\Column(name="valid", type="boolean", nullable=true)
	 */
	private $valid;

	/**
	 * @var bool|null
	 * @ORM\Column(name="large", type="boolean", nullable=true)
	 */
	private $large;

	/**
	 * @var int|null
	 * @ORM\Column(name="process_started_at", type="integer", nullable=true)
	 */
	private $processStartedAt;

	/**
	 * @var int|null
	 * @ORM\Column(name="process_completed_at", type="integer", nullable=true)
	 */
	private $processCompletedAt;

	/**
	 * @var OfferEntity[]
	 * @ORM\OneToMany(targetEntity="OfferEntity", mappedBy="updateFeed", fetch="EXTRA_LAZY")
	 */
	private $offers;


	const STATUS_DOWNLOADING = 'Downloading';
	const STATUS_DOWNLOADED = 'Downloaded';
	const STATUS_DOWNLOADED_ERROR = 'Download Error';
	const STATUS_IMPORTING = 'Importing';
	const STATUS_IMPORTED = 'Imported';
	const STATUS_IMPORTED_ERROR = 'Import Error';

	public function __construct() {
		$this->setCreatedAt();
		$this->skipError = true;
		$this->forceUpdate = true;
		$this->offers = new ArrayCollection();
		$this->setStatus(self::STATUS_DOWNLOADING);
	}

	/**
	 * @return string
	 */
	public function getSourceUrl(): string {
		return $this->sourceUrl;
	}

	/**
	 * @param string $sourceUrl
	 */
	public function setSourceUrl(string $sourceUrl): void {
		$this->sourceUrl = $sourceUrl;
	}

	/**
	 * @return string|null
	 */
	public function getUrl(): ?string {
		return $this->url;
	}

	/**
	 * @param string|null $url
	 */
	public function setUrl(?string $url): void {
		$this->url = $url;
	}

	/**
	 * @return bool
	 */
	public function isSkipError(): bool {
		return $this->skipError;
	}

	/**
	 * @param bool $skipError
	 */
	public function setSkipError(bool $skipError): void {
		$this->skipError = $skipError;
	}

	/**
	 * @return bool
	 */
	public function isForceUpdate(): bool {
		return $this->forceUpdate;
	}

	/**
	 * @param bool $forceUpdate
	 */
	public function setForceUpdate(bool $forceUpdate): void {
		$this->forceUpdate = $forceUpdate;
	}

	/**
	 * @return bool|null
	 */
	public function getValid(): ?bool {
		return $this->valid;
	}

	/**
	 * @param bool|null $valid
	 */
	public function setValid(?bool $valid): void {
		$this->valid = $valid;
	}

	/**
	 * @return bool|null
	 */
	public function getLarge(): ?bool {
		return $this->large;
	}

	/**
	 * @param bool|null $large
	 */
	public function setLarge(?bool $large): void {
		$this->large = $large;
	}


	/**
	 * @return int|null
	 */
	public function getProcessStartedAt(): ?int {
		return $this->processStartedAt;
	}

	/**
	 * @param int|null $processStartedAt
	 */
	public function setProcessStartedAt(?int $processStartedAt): void {
		$this->processStartedAt = $processStartedAt;
	}

	/**
	 * @return int|null
	 */
	public function getProcessCompletedAt(): ?int {
		return $this->processCompletedAt;
	}

	/**
	 * @param int|null $processCompletedAt
	 */
	public function setProcessCompletedAt(?int $processCompletedAt): void {
		$this->processCompletedAt = $processCompletedAt;
	}

	/**
	 * @return string
	 */
	public function getSkipErrorText() {
		return $this->isSkipError() ? 'Yes' : 'No';
	}

	/**
	 * @return string
	 */
	public function getForceUpdateText() {
		return $this->isForceUpdate() ? 'Yes' : 'No';
	}

	/**
	 * @return string
	 */
	public function getStatus(): string {
		return $this->status;
	}

	/**
	 * @param string $status
	 */
	public function setStatus(string $status): void {
		$this->status = $status;
	}

	/**
	 * @return OfferEntity[]
	 */
	public function getOffers() {
		return $this->offers;
	}

	/**
	 * @param OfferEntity[] $offers
	 */
	public function setOffers($offers): void {
		$this->offers = $offers;
	}

	public function isDownloading() {
		return self::STATUS_DOWNLOADING == $this->status;
	}

	public function isDownloaded() {
		return self::STATUS_DOWNLOADED == $this->status;
	}

	public function isDownloadedError() {
		return self::STATUS_DOWNLOADED_ERROR == $this->status;
	}

	public function isImporting() {
		return self::STATUS_IMPORTING == $this->status;
	}

	public function isImported() {
		return self::STATUS_IMPORTED == $this->status;
	}

	public function isImportedError() {
		return self::STATUS_IMPORTED_ERROR == $this->status;
	}
}

src/Entity/Traits/CreatedTrait.php
<?php


namespace App\Entity\Traits;


use App\Utils\Config;

Trait CreatedTrait
{
	/**
	 * @var int
	 * @ORM\Column(name="created_at", type="integer", nullable=false)
	 */
	private $createdAt;

	/**
	 * Get createdAt
	 *
	 * @param bool $formatted
	 * @return int
	 */
	public function getCreatedAt($formatted = true)
	{
		if ($formatted) {
			return $this->createdAt ? date(Config::DATETIME_FORMAT, $this->createdAt) : null;
		}
		return $this->createdAt;
	}

	/**
	 * @return string
	 */
	public function getCreatedAtFormatted() {
		return $this->getCreatedAt(true);
	}

	/**
	 * @return string
	 */
	public function getCreatedAtDateFormatted() {
		return date(Config::DATE_FORMAT, $this->createdAt);
	}

	/**
	 * Set createdAt
	 *
	 * @param int $createdAt | null
	 *
	 * @return $this
	 */
	public function setCreatedAt($createdAt = null)
	{
		if ($createdAt == null) {
			$this->createdAt = time();
		} else {
			$this->createdAt = $createdAt;
		}

		return $this;
	}


}

src/Form/FeedType.php
<?php


namespace App\Form;


use App\Entity\FeedEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FeedType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->add('sourceUrl', TextType::class, [
				'label' => 'Import Offer JSON URL (required)',
				'help' => 'Please enter a valid offer json URL',
				'attr' => ['placeholder' => 'http://127.0.0.1:8000/c51.json'],
			])
			->add('skipError', ChoiceType::class, [
				'label' => 'Skip Error Offer (required)',
				'choices' => array_flip([0 => 'No', 1 => 'Yes']),
				'attr' => ['class' => 'chosen'],
				'help' => 'Import will skip error offer data (offerId is numeric and > 0, cash back is > 0)',
			])
			->add('forceUpdate', ChoiceType::class, [
				'label' => 'Force Update (required)',
				'choices' => array_flip([false => 'No', true => 'Yes']),
				'attr' => ['class' => 'chosen'],
				'help' => 'Update existing offer data',
			])
			;
	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([
			'data_class' => FeedEntity::class,
		]);
	}
}

src/Controller/FeedController.php
<?php


namespace App\Controller;


use App\Entity\FeedEntity;
use App\Exception\DownloadFailedException;
use App\Exception\ImportOfferException;
use App\Form\FeedType;
use App\Repository\FeedRepository;
use App\Service\FeedService;
use App\Service\OfferService;
use App\Utils\Config;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/feed")
 */
class FeedController extends BaseController
{
	/**
	 * @var FeedService
	 */
	private $feedService;

	/**
	 * @var OfferService
	 */
	private $offerService;

	/**
	 * @var PaginatorInterface
	 */
	private $paginator;

	/**
	 * @var ParameterBagInterface
	 */
	private $parameterBag;

	/**
	 * FeedController constructor.
	 * @param PaginatorInterface $paginator
	 * @param FeedService $feedService
	 * @param OfferService $offerService
	 */
	public function __construct(PaginatorInterface $paginator, FeedService $feedService, OfferService $offerService, ParameterBagInterface $parameterBag) {
		$this->paginator = $paginator;
		$this->feedService = $feedService;
		$this->offerService = $offerService;
		$this->parameterBag = $parameterBag;
	}

	/**
	 * @Route("/", name="feed_index", methods="GET")
	 * @param Request $request
	 * @param FeedRepository $feedRepository
	 * @return Response
	 */
	public function indexAction(Request $request, FeedRepository $feedRepository) {
		$data = [
			'title' => 'Feeds',
			'form' => [
				'page' => $request->query->getInt('page', 1),
			]
		];
		$feedQuery = $feedRepository->findAllFeedsQuery();
		$data['pagination'] = $this->paginator->paginate($feedQuery, $data['form']['page'], Config::PAGE_LIMIT);

		return $this->render('feed/index.html.twig', $data);
	}

	/**
	 * @Route("/new", name="feed_new", methods="GET|POST")
	 * @param Request $request
	 * @return Response
	 */
	public function newAction(Request $request) {
		$feed = new FeedEntity();
		$form = $this->createForm(FeedType::class, $feed);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$this->feedService->saveOrUpdateFeed($feed);
			return $this->redirectToRoute('feed_download', ['id' => $feed->getId()]);
		}

		return $this->render('feed/new.html.twig', [
			'title' => 'Import Feed',
			'form' => $form->createView(),
		]);
	}

	/**
	 * @Route("/download/{id}", requirements={"id"="\d+"}, name="feed_download", methods="GET")
	 * @param int $id
	 * @param FeedRepository $feedRepository
	 * @return Response
	 */
	public function downloadAction($id, FeedRepository $feedRepository) {
		try {
			$feed = $this->feedService->processFeed($id);
		} catch (DownloadFailedException $e) {
			$feed = $feedRepository->find($id);
		}

		return $this->render('feed/download.html.twig', [
			'title' => 'Download Feed',
			'wsHost' => $this->parameterBag->get('ws_host'),
			'wsPort' => $this->parameterBag->get('ws_port'),
			'feed' => $feed
		]);
	}

	/**
	 * @Route("/import/{id}", requirements={"id"="\d+"}, name="feed_import", methods="POST")
	 * @param int $id
	 * @return Response
	 */
	public function importAction($id) {
		//check if feed is already downloaded
		//check file chunksum and valid
		try {
			$this->offerService->processOffers($id);
		} catch (ImportOfferException $e) {
			return $this->redirectToRoute('feed_download', ['id' => $id]);
		}

		return $this->redirectToRoute('offer_index', ['feedId' => $id]);
	}

	/**
	 * For testing purpose
	 * @Route("/delete", name="feed_delete", methods="GET")
	 * @return Response
	 */
	public function deleteAction() {
		$this->getDoctrine()->getConnection()->exec('delete from offer');
		$this->getDoctrine()->getConnection()->exec('delete from feed');
		return $this->redirectToRoute('feed_index', []);
	}

}

templates/feed/download.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <!-- general form elements disabled -->
                <div class="box box-solid">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-12 text-center">
                            <div class="alert
                                {% if feed.downloadedError or feed.importedError  %} alert-danger {% else %} alert-info {% endif %} ">{{ feed.status }}</div>
                        </div>

                        <div class="col-md-12">
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <th class="col-md-4">ID</th>
                                    <td class="col-md-8">{{ feed.id }}</td>
                                </tr>
                                <tr>
                                    <th>Source URL</th>
                                    <td>{{ feed.sourceUrl }}</td>
                                </tr>
                                <tr>
                                    <th>Skip Error</th>
                                    <td>{{ feed.skipErrorText }}</td>
                                </tr>
                                <tr>
                                    <th>Force Update</th>
                                    <td>{{ feed.forceUpdateText }}</td>
                                </tr>
                            </table>
                        </div>

                        <div class="col-md-12 text-center">

                            {% if feed.downloaded %}
                                <form action="/feed/import/{{ feed.id }}" method="post">
                                    <button class="btn btn-primary"
                                        type="submit">{{ button_label|default('Import') }}</button>
                                </form>
                            {% elseif feed.imported %}
                                <a class="btn btn-primary" href="{{ path('offer_index', {'feedId' : feed.id}) }}" type="button">View Offers</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if feed.id is defined %}
    {% include "popup.modal.html.twig" with {feedId: feed.id, wsHost: wsHost, wsPort: wsPort} %}
    {% endif %}
{% endblock %}

templates/feed/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    {% include "app.session.flashbag.html.twig" %}
                    <h3 class="box-title">Total: ({{ pagination.getTotalItemCount }})</h3>
                    <div class="pull-right">
                        <a href="{{ path('feed_new') }}" type="button" class="btn btn-primary">Add Feed</a>
                        <a href="{{ path('feed_delete') }}" type="button" class="btn btn-danger">Delete Feeds & Offers </a>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th class="col-md-1">ID</th>
                                <th class="col-md-3">Source URL</th>
                                <th class="col-md-1">Skip Error</th>
                                <th class="col-md-1">Force Update</th>
                                <th class="col-md-2">Created</th>
                                <th class="col-md-2">Status</th>
                                <th class="col-md-2">Offers</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% if pagination.getTotalItemCount %}
                                {% for item in pagination %}
                                    <tr>
                                        <td>
                                            <a href="{{ path('feed_download', {'id': item.id}) }}">{{ item.id }}</a>
                                        </td>
                                        <td>{{ item.sourceUrl }}</td>
                                        <td>{{ item.skipErrorText }}</td>
                                        <td>{{ item.forceUpdateText }}</td>
                                        <td>{{ item.createdAtFormatted }}</td>
                                        <td>
                                            {{ item.status }}
                                            {% if item.downloaded %}
                                                <a href="{{ path('feed_download', {'id': item.id}) }}"> (Import Offers) </a>
                                            {% elseif (item.downloading) %}
                                                <a href="{{ path('feed_download', {'id': item.id}) }}"> (View Download) </a>
                                            {% endif %}
                                        </td>
                                        <td><a href="{{ path('offer_index', {'feedId': item.id}) }}">{{ item.offers.count }}</a></td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="12" class="alert">No records found</td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix">
                    <div class="no-margin pull-right">
                        {{ knp_pagination_render(pagination) }}
                    </div>
                </div>
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

{% endblock %}

templates/feed/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-12">
            <!-- general form elements disabled -->
            <div class="box">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-success alert-dismissible">
                                <ul>
                                    <li>Small feed file sample URL <a target="_blank" href="/small.json">(Small Feed)</a></li>
                                    <li>Large feed file sample URL <a target="_blank" href="/large.json">(Large Feed)</a></li>
                                    <li>Dummy JSON file sample URL <a target="_blank" href="/invalid.json">(Dummy JSON Feed)</a></li>
                                    <li>None JSON file sample URL <a target="_blank" href="/notjson.txt">(Not JSON Feed)</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <a class="btn btn-danger" href="{{ path('feed_index') }}">{{ 'Back'|trans }}</a>
                    <button class="btn btn-primary" type="submit">{{ button_label|default('Start Importing') }}</button>
                    {{ form_end(form) }}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
{% endblock %}